### ISSUE TITLE
update ?

### ISSUE THREAD

**Issue by Smiley-k** [jul-m/archires#3]
does not work with glpi version 9.1.1

**Comment by jul-m** [comment]
It will be necessary to check if they provided for an update of the official version of the plugin (https://forge.glpi-project.org/projects/archires). If they have not planned to update soon, I will be able to work on it if I have the time.

**Comment by Alwaysin** [comment]
```
Version 2.3 
Compatible glpi >= 0.90 and < 9.1
```

Unfortunately no new version compatible :(
@jul-m if you have time... :D
